version: '3.9'

services:
  go-app:
    container_name: go-app
    build: .
    environment:
      DB_URL: "host=localhost user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "9000:9000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: soetan.dev@example.com
      PGADMIN_DEFAULT_PASSWORD: 1993
    ports:
        - "5050:80"

volumes:
  pgdata: {}